### ISSUE TITLE
Event pagination on blocks not working

### ISSUE THREAD

**Issue by jfrank-summit** [autonomys/astral#1001]
As an example: There is 44 events on block [321500 ](https://astral.autonomys.xyz/mainnet/consensus/blocks/321500), but only10 are visible on the page and it shows that there is just one page out of one available when five would be expected. Changing view to show 50 results all events are visible. Also, navigation buttons are not disabled regardless of whether they can be pressed.

**Comment by marc-aurele-besner** [comment]
This was addressed in #992, it's just not pushed to prod yet, I opened #1002 to sync the production branch

**Comment by jfrank-summit** [comment]
Fixed in #992 .
