### ISSUE TITLE
Extrinsics filtering is broken

### ISSUE THREAD

**Issue by EmilFattakhov** [autonomys/astral#474]
When trying to filter by the module - getting the infinite loading spinner with no results.

**Comment by natachadelarosa** [comment]
I reviewed the database calls with the logging dashboards in Graphana that Muhammad helped me set and couldn't get to the specific issue, thought the queries were reaching the database without the proper filters but that is not the case, I'm currently working on squids separation, and will revisit after those are applied to check if will be still happening.

**Comment by marc-aurele-besner** [comment]
I fixed the modules not showing in the dropdown and made various improvements, especially memoization-related ones.
The problem persists and seems to be related to the size of the extrinsic table, resulting in the request timing out before resolving.

**Comment by marc-aurele-besner** [comment]
This issue was fix when moving to SubQuery
