### ISSUE TITLE
"Raw status" doubled 

### ISSUE THREAD

**Issue by DianaPertseva** [autonomys/astral#841]
On the page https://astral.autonomys.xyz/gemini-3h/staking filter has "Raw status" doubled 
<img width="513" alt="Screenshot 2024-09-02 at 12 48 36 PM" src="https://github.com/user-attachments/assets/fe3e0535-c82f-4228-8f5e-5580db67e20f">

**Comment by marc-aurele-besner** [comment]
This issue is solved in the main branch https://github.com/autonomys/astral/pull/829
