### ISSUE TITLE
Astral explorer throw an error when sitting unused for a long period of time

### ISSUE THREAD

**Issue by marc-aurele-besner** [autonomys/astral#980]
## Astral Explorer throw an error when sitting unused for a long period

It seems that when the tabs are left inactive for a long period of time, an error bubbles up and causes the error screen to appear.

**Comment by jfrank-summit** [comment]
If this is the same error I'm seeing, I noticed today that this shifted from "a long period" to sometimes a very short (seconds) period. Could it be from increased load?

**Comment by marc-aurele-besner** [comment]
Yes, this is very likely due to increase load, we have scale up the server on green mainnet, I synced the branch (as this server was very behind on many changes we had push), wiped the volumes and started the indexing, as soon as green is synced. I'll switch the load over on green, and we will scale blue similarly.

I also enable subscription on Hasura on green, so this will allow me to start working on changing the FE logic to use subscription, especially on the most visited page, like Home, this should help a lot, as usually many users hook the the same subscription query reduce load a lot
