### ISSUE TITLE
Search on Accounts page is searching extrinsics

### ISSUE THREAD

**Issue by jfrank-summit** [autonomys/astral#981]
The search box on [Accounts](https://astral.autonomys.xyz/mainnet/consensus/accounts) page is actually searching extrinsics. If you put a value in to search it will route to the extrinsic page. See images below.

![image](https://github.com/user-attachments/assets/af7d74e7-597b-4ea7-92fb-1caf1c5aee94)
Searching for address
![image](https://github.com/user-attachments/assets/51cc77a2-73ad-4479-91da-1b1e44472b03)
Leads to extrinsic route with the searched address
![image](https://github.com/user-attachments/assets/94ea9ba2-f9e1-41b6-ba2e-655220589977)

**Comment by marc-aurele-besner** [comment]
I re-work these significantly recently, look at the dev environment https://dev-astral.netlify.app/mainnet/consensus/accounts

I remove the main search bar on these page in favor of the search pannel with different search options

**Comment by jfrank-summit** [comment]
Nice! Closing as no longer relevant.
